export const items = [
  {
    id: 1,
    name: "Nike Air Force 1 LV8",
    desc: "Big Kids' Shoes",
    price: 72.97,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/8482e6fb-0279-4ca7-8120-08210be39584/air-force-1-lv8-big-kids-shoes-jgTnLK.png",
    category: "shoes",
    age: "kids",
    gender: "boys",
  },
  {
    id: 2,
    name: "Air Jordan 9 Retro",
    desc: "Big Kids' Shoes",
    price: 150,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/35fd1adb-0c70-47ec-a8a2-97f5b4fa6fe9/air-jordan-9-retro-big-kids-shoes-jBvcFR.png",
    category: "shoes",
    age: "kids",
    gender: "boys",
  },
  {
    id: 3,
    name: "Nike Sportswear Club",
    desc: "Big Kids' Pullover Hoodie",
    price: 38.97,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7863646d-897c-49bd-9ba7-e918919e9ade/sportswear-club-big-kids-pullover-hoodie-qRKg36.png",
    category: "clothing",
    age: "kids",
    gender: "boys",
  },
  {
    id: 4,
    name: "Nike Sportswear Tech Fleece",
    desc: "Big Kids' (Boys') Pants",
    price: 75,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e7795c32-2eb6-4eba-91f9-9955b61d4ac6/sportswear-club-fleece-big-kids-boys-joggers-VjhJzZ.png",
    category: "clothing",
    age: "kids",
    gender: "boys",
  },
  {
    id: 5,
    name: "Nike Air Vapormax 2021 Fkyknit",
    desc: "Men's Shoes",
    price: 250,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f51a5a20-6489-4a16-b6cc-76ea240b5615/air-vapormax-2021-flyknit-mens-shoes-NpTfFz.png",
    category: "shoes",
    age: "men",
  },
  {
    id: 6,
    name: "Nike Air Max 270",
    desc: "Men's Shoes",
    price: 160,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a52e5eb5-17a1-48c5-9ee1-08b048d8d69c/air-max-270-mens-shoes-KkLcGR.png",
    category: "shoes",
    age: "men",
  },
  {
    id: 7,
    name: "Nike Dri-FIT Element",
    desc: "Men's 1/4-Zip Running Top",
    price: 75,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/0942e91c-d2b4-4e45-8f1c-d97f72239d3e/dri-fit-element-mens-1-4-zip-running-top-q04tXT.png",
    category: "clothing",
    age: "men",
  },
  {
    id: 8,
    name: "Nike Sportswear Windrunner",
    desc: "Men's Hooded Jacket",
    price: 85,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/2f949624-8215-4b9b-b0e6-e9df5a9f83e5/sportswear-windrunner-mens-hooded-jacket-5hK13x.png",
    category: "clothing",
    age: "men",
  },
  {
    id: 9,
    name: "Nike Element",
    desc: "Women's 1/2-Zip Running Top",
    price: 85,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4cd3ab73-5781-4d8b-8583-4bcf1da51984/element-womens-1-2-zip-running-top-b1BCVg.png",
    category: "clothing",
    age: "women",
  },
  {
    id: 10,
    name: "Nike Dri-FIT ADV AeroSwift",
    desc: "Women's Running Crop Top",
    price: 70,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/47f84eae-30bc-443e-91bb-9de9cbdf2114/dri-fit-adv-aeroswift-womens-running-crop-top-C5VHR8.png",
    category: "clothing",
    age: "women",
  },
  {
    id: 11,
    name: "Nike Air Max 270",
    desc: "Men's Hooded Jacket",
    price: 85,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/25340310-487f-4816-8887-bca7e49f7019/air-max-270-womens-shoes-Pgb94t.png",
    category: "shoes",
    age: "women",
  },
  {
    id: 12,
    name: "Nike Mecton 8 AMP",
    desc: "Women's Training Shoes",
    price: 120,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a434379e-98ac-4b7a-bb31-5b179e9a010b/metcon-8-amp-womens-training-shoes-Hzmjkl.png",
    category: "shoes",
    age: "women",
  },
  {
    id: 13,
    name: "Nike Basketball",
    desc: "Kids (Size 3)",
    price: 29.99,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/v3lgobpxv6kp6g1tvgg3/skills-basketball-size-3-YPTAr4ED.png",
    category: "gear",
    age: "kids",
  },
  {
    id: 14,
    name: "Jordan Backpack",
    desc: "Backpack (Large)",
    price: 120,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/dt1adtqjetwdfn347gcj/jordan-backpack-large-HM2JGJ.png",
    category: "gear",
    age: "all",
  },
  {
    id: 15,
    name: "Nike HyperCharge TR 12oz",
    desc: "Straw Water Bottle",
    price: 24.95,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/eb44f267-b973-4f56-aaea-ca83e97022b1/hypercharge-tr-12oz-straw-water-bottle-x4stKf.png",
    category: "gear",
    age: "all",
  },
  {
    id: 16,
    name: "Nike Fuel Pack",
    desc: "Lunch Bag",
    price: 29.98,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/02cb728d-f395-40c7-a66c-e8254f3d5535/fuel-pack-lunch-bag-JqCmcz.png",
    category: "gear",
    age: "women",
  },
  {
    id: 17,
    name: "Nike Sportswear Fly",
    desc: "Big Kids' Girls Pullover Hoodie",
    price: 49.94,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd31bd79-85f3-44f3-b482-75f0922be048/sportswear-fly-big-kids-girls-pullover-hoodie-sJS70q.png",
    category: "clothing",
    age: "kids",
    gender: "girls",
  },
  {
    id: 18,
    name: "Nike Sportswear Club Fleece",
    desc: "Big Kids' (Girls') Pants",
    price: 29.97,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ccd6648f-3b1f-4362-ba34-30fe20dbc7e7/sportswear-club-fleece-big-kids-girls-pants-extended-size-blrF0J.png",
    category: "clothing",
    age: "kids",
    gender: "girls",
  },
  {
    id: 19,
    name: "Nike Downshifter 12",
    desc: "Big Kids' Road Running Shoes",
    price: 29.98,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7fcf8070-1e2a-4cb3-8ce0-484f79a22701/downshifter-12-big-kids-road-running-shoes-2Gv6tP.png",
    category: "shoes",
    age: "kids",
    gender: "girls",
  },
  {
    id: 20,
    name: "Lebron XXX",
    desc: "Big Kids' Basketball Shoes",
    price: 160,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/98b886d4-60ad-4ea8-9258-c6330501e194/lebron-xx-big-kids-basketball-shoes-03km3N.png",
    category: "shoes",
    age: "kids",
    gender: "girls",
  },
  {
    id: 21,
    name: "Nike Air Zoom",
    desc: "Soccer Cleats",
    price: 260,
    src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7d380f24-7f1b-421d-aa00-5c1f896934cc/zoom-mercurial-superfly-9-elite-fg-firm-ground-soccer-cleats-sb8gJK.png",
    category: "shoes",
    age: "men",
  },
];
